### ISSUE TITLE
按照readme都按照这样配置了 还是没有想数据库查数据啊 easy_retry_task里面还是查询不到数据啊

### ISSUE THREAD

**Issue by cckmit** [alibaba/easy-retry#20]
easy_retry_task

**Comment by cckmit** [comment]
![image](https://user-images.githubusercontent.com/28696425/140024915-bdd6b6b5-f751-4b30-88c1-16d6d1a580d0.png)

**Comment by cckmit** [comment]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
	at com.alibaba.easyretry.core.PersistenceRetryer.call(PersistenceRetryer.java:31)
	at com.alibaba.easyretry.extension.spring.aop.RetryInterceptor.around(RetryInterceptor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)

**Comment by cckmit** [comment]
at com.alibaba.easyretry.core.PersistenceRetryer.call(PersistenceRetryer.java:31)
at com.alibaba.easyretry.extension.spring.aop.RetryInterceptor.around(RetryInterceptor.java:51) 走到easyretry

**Comment by cckmit** [comment]
可以了
